# LEARNING NUMPY WITH SCALAR

first learning in datascience

In [32]:
import numpy as np
python_list = [1, 5, 3, 6, -8]
python_list


[1, 5, 3, 6, -8]

In [33]:
numpy_arr = np.array(python_list)
len(numpy_arr.shape)

1

In [34]:
python_list_list = [[1,2],[3,4]]
python_list_list

[[1, 2], [3, 4]]

In [35]:
np.array(python_list_list)


array([[1, 2],
       [3, 4]])

In [36]:
numpy_arr2 = np.array(python_list_list)
numpy_arr2.shape

(2, 2)

In [37]:
list(range(8))

[0, 1, 2, 3, 4, 5, 6, 7]

In [38]:
np.arange(8)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [39]:
np.zeros((2, 2, 2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [40]:
np.random.randint(5, size =(2,2) )

array([[2, 1],
       [1, 0]])

In [41]:
#checking datatype
import numpy as np
a = [1, 2, 3, 4, 5, 6, 45]
arr = np.array(a)
arr.dtype

dtype('int32')

In [42]:
#slicing
import numpy as np

In [2]:
arr = np.random.rand(5, 5)

In [3]:
arr

array([[0.49345006, 0.04845642, 0.84439427, 0.26093915, 0.61601445],
       [0.81201042, 0.85788424, 0.18677827, 0.07852011, 0.51701174],
       [0.81184528, 0.5211269 , 0.54501328, 0.9361325 , 0.39764387],
       [0.33317612, 0.92702355, 0.72231174, 0.11281185, 0.41475667],
       [0.46639318, 0.03916971, 0.76474183, 0.39224889, 0.78366749]])

In [5]:
arr.shape

(5, 5)

In [7]:
arr.dtype

dtype('float64')

In [9]:
 arr[:4]

array([[0.49345006, 0.04845642, 0.84439427, 0.26093915, 0.61601445],
       [0.81201042, 0.85788424, 0.18677827, 0.07852011, 0.51701174],
       [0.81184528, 0.5211269 , 0.54501328, 0.9361325 , 0.39764387],
       [0.33317612, 0.92702355, 0.72231174, 0.11281185, 0.41475667]])

In [11]:
arr[:, :4]   #remove last row

array([[0.49345006, 0.04845642, 0.84439427, 0.26093915],
       [0.81201042, 0.85788424, 0.18677827, 0.07852011],
       [0.81184528, 0.5211269 , 0.54501328, 0.9361325 ],
       [0.33317612, 0.92702355, 0.72231174, 0.11281185],
       [0.46639318, 0.03916971, 0.76474183, 0.39224889]])

In [12]:
arr[1,1]    #selet 1 number

0.8578842416807837

In [13]:
arr[: -1] #delete the last row

array([[0.49345006, 0.04845642, 0.84439427, 0.26093915, 0.61601445],
       [0.81201042, 0.85788424, 0.18677827, 0.07852011, 0.51701174],
       [0.81184528, 0.5211269 , 0.54501328, 0.9361325 , 0.39764387],
       [0.33317612, 0.92702355, 0.72231174, 0.11281185, 0.41475667]])

In [19]:
#masking
int_arr = np.random.randint(5, size=(6,8))

In [22]:
int_arr

array([[0, 4, 3, 4, 2, 0, 0, 4],
       [1, 2, 1, 2, 3, 4, 2, 1],
       [2, 2, 1, 4, 0, 4, 0, 2],
       [4, 4, 3, 1, 3, 0, 0, 2],
       [3, 1, 1, 1, 2, 3, 4, 1],
       [3, 1, 3, 1, 0, 3, 1, 1]])

In [23]:
int_arr_0 = int_arr[0]      #selecting first row only
int_arr_0

array([0, 4, 3, 4, 2, 0, 0, 4])

In [24]:
int_arr_0 == 0

array([ True, False, False, False, False,  True,  True, False])

In [27]:
int_arr_0 == 2

array([False, False, False, False,  True, False, False, False])

In [29]:
#this line check wheather my current element is 0,2 or 1
int_arr0_is12 = (int_arr_0 == 0) | (int_arr_0 == 2) | (int_arr_0 == 1)

In [30]:
int_arr0_is12

array([ True, False, False, False,  True,  True,  True, False])

In [31]:
int_arr_0[int_arr0_is12]

array([0, 2, 0, 0])

In [43]:
#transpose
import numpy as np

In [5]:
marks = [[1,2,3,4],[5,6,7,8],[9,10,11,12]]
marks[0]

[1, 2, 3, 4]

In [53]:
marks[0][0], marks[1][0], marks[2][0]

(1, 5, 9)

In [55]:
marks_transpose = []
for j in range(len(marks[0])):
    marks_transpose.append([])
    for i in range(len(marks)):
        marks_transpose[j].append(marks[i][j])

In [56]:
marks_transpose

[[1, 5, 9], [2, 6, 10], [3, 7, 11], [4, 8, 12]]

In [57]:
#transpose using numpy
marks_array = np.array(marks)

In [28]:
marks_array

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [59]:
marks_array.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [60]:
marks_array.sum(axis=1)

array([10, 26, 42])

In [61]:
marks_array.sum(axis=1)/60*100

array([16.66666667, 43.33333333, 70.        ])

In [63]:
marks_array.T.sum(axis=1)

array([15, 18, 21, 24])

In [64]:
#numpy:BROADCASTING--adding new vector, Applying an operation to multiple elements of an array
marks_array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [67]:
grace_marks = np.array([[1,2,3]]).T
grace_marks

array([[1],
       [2],
       [3]])

In [68]:
grace_marks+marks_array

array([[ 2,  3,  4,  5],
       [ 7,  8,  9, 10],
       [12, 13, 14, 15]])

In [69]:
grace_marks.shape

(3, 1)

# numpy: Matrix multiplication
Given matrix of marks of 3 students in Maths, Physics, Chemistry & Biology respectively

We want to give students a final score, by giving 40% weightage to Math, 20% each to Physics, Chemistry & Biology

In [24]:
weight_list = [[0.4], [0.2], [0.2], [0.2]]

In [35]:
weight_list

[[0.4], [0.2], [0.2], [0.2]]

In [36]:
marks

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]

In [37]:
results = []
for i in range(len(marks)):
    for j in range(len(weight_lists)):
        #marks[i]*weight_lists[j]
        curr_sum = 0
        for k in range(len(marks[i])):
            curr_sum += marks[i][k]*weight_lists[k][j]
        results.append(curr_sum)
            

NameError: name 'weight_lists' is not defined

In [14]:
results

[2.2, 6.200000000000001, 10.2]

In [32]:
marks_array

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]